name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on: 
  workflow_dispatch:
env:
  RELEASE_DIR: bin/Release/

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release
      env: 
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - uses: actions/upload-artifact@v2
      with:
        name: PluginRepoZip
        path: ${{ env.RELEASE_DIR }}
        if-no-files-found: error
