name: .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  workflow_dispatch:

env:
  PROJECT_NAME: MZRadialMenu

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
          7z e latest.zip -o $HOME/.xlcore/dalamud/Hooks/dev
      - name: Build
        run: |
          dotnet build --configuration Release --nologo
      - name: Archive
        run: 7z a $PROJECT_NAME.zip bin/release/*
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            MZRadialMenu.zip
